controllers_admin:
  resource: ../../src/AdminBundle/config/routes.yaml
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

controllers_front:
  resource: ../../src/Controller/Front
  type: attribute
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

controllers_commerce:
  resource: ../../src/Commerce/Controller
  type: attribute
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

controllers_catalog:
  resource: ../../src/Catalog/Controller
  type: attribute
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

oauth:
  resource: ../../src/OAuthBundle/config/routes.yaml
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

seo:
  resource: ../../src/SeoBundle/config/routes.yaml

kernel:
  resource: ../../src/Kernel.php
  type: attribute
