controllers_admin:
  resource: ../../src/Controller/Admin
  type: attribute
  #type: annotation
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

controllers_front:
  resource: ../../src/Controller/Front
  type: attribute
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

controllers_robots_txt:
  resource: ../../src/Controller/Front/RobotsTxtController.php
  type: attribute
  format: txt
  requirements:
    _format: txt

controllers_sitemap:
  resource: ../../src/Controller/Front/SitemapController.php
  type: attribute
  format: xml
  requirements:
    _format: xml

kernel:
  resource: ../../src/Kernel.php
  type: attribute
