seo_robots:
  resource: ../Controller/RobotsTxtController.php
  type: attribute
  format: txt
  requirements:
    _format: txt

seo_sitemap:
  resource: ../Controller/SitemapController.php
  type: attribute
  format: xml
  requirements:
    _format: xml
